### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by kdavis37** [inventit/processing-android-serial#5]
I am pretty new to writing code for android. I found a tutorial that used processing-android-serial and I compiled the files. Upon running the code on my device I receive an error. It occurs on import com.yourinventit.processing.android.serial.*; My question would be have I added the library wrong or what could cause an error similar to this. I will paste the debug information below.  I will appreciate any help you can give me.

FATAL EXCEPTION: Animation Thread
Process: processing.test.testa, PID: 4655
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yourinventit/processing/android/serial/Serial;
	at processing.test.testa.testa.setup(testa.java:39)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yourinventit.processing.android.serial.Serial" on path: DexPathList[[zip file "/data/app/processing.test.testa-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 5 more
	Suppressed: java.lang.ClassNotFoundException: com.yourinventit.processing.android.serial.Serial
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 6 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by dbaba** [comment]
The error `ClassNotFoundException` tells your APK doesn't include the processing-android-serial library (jar file of this project). Please make sure that your project include the jar file and the built APK should contain it.

**Comment by kdavis37** [comment]
In processing I went to Sketch -> Add File... and added the three jar files from The AndroidSerial/library directory and that solved the problem.  Thank you.
